version: '3'

services:
  api01: &api
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./framework:/var/www/html/framework
      - ./config:/var/www/html/config
      - ./logs:/var/www/html/logs
      - ./database/Migration:/var/www/html/database/Migration
    ports:
      - '5000:9999'
    tty: true
    stdin_open: true
    environment:
      - PORT=9999
      - DB_DRIVER=${DB_DRIVER}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - DB_HOST=banco_de_dados_relacional
      - JWT_KEY=${JWT_KEY}
      - LOG_STORAGE=logs/app.log
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    ##deploy:
    ##  replicas: 2
    networks:
      - cascata
  api02:
    <<: *api
    ports:
      - '10000:7777'
    environment:
      - PORT=7777
      - DB_DRIVER=${DB_DRIVER}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - DB_HOST=banco_de_dados_relacional
      - JWT_KEY=${JWT_KEY}
      - LOG_STORAGE=logs/app.log
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    networks:
      - cascata
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/access.log:/var/log/nginx/access.log
    depends_on:
      - api01
      - api02
    ports:
      - "8888:8888"
    networks:
      - cascata
  banco_de_dados_em_memoria:
    image: memcached:1.6.21
    ports:
      - '11211:11211'
    command: -m 64
    networks:
      - cascata
  banco_de_dados_relacional:
    #image: mysql:5.7
    image: mysql:latest
    expose:
      - "3306"
    ports:
      - '5306:3306'
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./docker/backup_banco_de_dados_relacional/database:/var/lib/mysql
    networks:
      - cascata
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      expose:
        - "80"
      ports:
        - "8003:80"
      volumes:
        - ./docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      environment:
        #PMA_ARBITRARY: 1
        PMA_HOST: banco_de_dados_relacional
      depends_on:
        - banco_de_dados_relacional
      networks:
        - cascata
  mensageria:
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - cascata
networks:
  cascata: