version: '3'

services:
  api01: &api
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./framework:/var/www/html/framework
      - ./config:/var/www/html/config
      - ./apiEnvs:/var/www/html/apiEnvs
      - ./Migrations:/var/www/html/Migrations
      - ./logs:/var/www/html/logs
    ports:
      - '9999:9999'
    tty: true
    stdin_open: true
  api02:
    <<: *api
    ports:
      - '10000:9999'
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/access.log:/var/log/nginx/access.log
    depends_on:
      - api01
      - api02
    ports:
      - "8888:9999"

  banco_de_dados_em_memoria:
    image: memcached:1.6.21
    ports:
      - '10211:11211'
    command: -m 64
  banco_de_dados_relacional:
    #image: mysql:5.7
    image: mysql:latest
    expose:
      - "3306"
    ports:
      - '5306:3306'
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: docker-php
    volumes:
      - ./backupBD/database:/var/lib/mysql
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      expose:
        - "80"
      ports:
        - "8003:80"
      volumes:
        - ./docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      environment:
        #PMA_ARBITRARY: 1
        PMA_HOST: banco_de_dados_relacional
      depends_on:
        - banco_de_dados_relacional
  mensageria:
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}